In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Datasets/Churn_rate_prediction.csv")

In [3]:
print(df.isna().sum().sum())
print()
print(df.shape)
print()
df.isna().sum()

0

(10000, 14)

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
df.sample(6)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9700,9701,15797149,Lloyd,563,Spain,Female,36,4,143680.47,2,1,1,63531.19,0
8336,8337,15788480,Pagnotto,786,Germany,Female,33,0,122325.58,1,0,0,34712.34,1
6744,6745,15611287,Chiu,777,France,Female,30,4,0.00,2,0,1,115611.97,0
4084,4085,15750458,Hawkins,693,France,Female,39,4,0.00,2,0,1,142331.39,0
7316,7317,15811690,Bayley,793,Germany,Male,54,2,128966.13,1,0,0,18633.40,1
7740,7741,15725906,Hankinson,665,Spain,Female,51,8,0.00,1,1,1,38928.48,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [6]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname                str
CreditScore          int64
Geography              str
Gender                 str
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [11]:
df.duplicated(subset='CustomerId').sum()        # checkig for duplicated based on customer id

np.int64(0)

In [20]:
df = df.drop(columns='Surname')

In [21]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [22]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [19]:
# checking for str data type columns to use OHE
df.select_dtypes(include='str').columns()

Index(['Surname', 'Geography', 'Gender'], dtype='str')

In [ ]:
# using OHE via 'get_dummies'

df = pd.get_dummies(df, columns=df.select_dtypes(include='str'), drop_first=True)

In [27]:
df.sample(10)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
1898,1899,15629078,850,45,5,127258.79,1,1,1,192744.23,1,True,False,False
1121,1122,15672704,809,24,4,0.00,2,1,0,193518.76,0,False,False,False
1424,1425,15596671,603,42,8,91611.12,1,0,0,144675.30,1,False,True,False
8273,8274,15709643,675,32,1,0.00,3,1,0,85901.09,0,False,False,True
1084,1085,15591257,796,24,8,0.00,2,1,0,61349.37,0,False,False,True
1632,1633,15745827,617,30,3,132005.77,1,1,0,142940.39,0,False,False,True
8484,8485,15601012,802,60,3,92887.06,1,1,0,39473.63,1,False,False,False
7443,7444,15707042,634,24,2,87413.19,1,1,0,63340.65,0,False,False,False
1233,1234,15575410,667,39,4,83765.35,2,1,0,118358.54,0,True,False,False
9338,9339,15691543,558,58,2,142537.18,1,1,1,88791.83,0,True,False,True

In [28]:
x = df.drop(columns='Exited')
y = df['Exited']

In [ ]:
from sklearn.preprocessing import StandardScaler